package(default_visibility = ["//visibility:public"])

cc_binary(
    name = "bad-db",
    srcs = ["main.cc"],
    deps = [
        "//lib:database",
        "//lib:file",
    ],
)

# cc_test(
#     name = "hello-success_test",
#     srcs = ["hello-world.cc"],
#     deps = [":hello-lib"],
# )

# cc_test(
#     name = "hello-fail_test",
#     srcs = ["hello-fail.cc"],
#     deps = [":hello-lib"],
# )

# filegroup(
#     name = "srcs",
#     srcs = glob(["**"]),
# )
