package(default_visibility = ["//visibility:public"])

cc_library(
    name = "database",
    srcs = ["database.cc"],
    hdrs = [
        "database.h",
        "file.h",
    ],
    visibility = [
        "//main:__pkg__",
        "//test:__pkg__",
    ],
)

cc_library(
    name = "file",
    srcs = ["file.cc"],
    hdrs = ["file.h"],
    visibility = [
        "//main:__pkg__",
        "//test:__pkg__",
    ],
)
